{{ #if cfg.shield_endpoint }}
shield_endpoint = '{{cfg.shield_endpoint}}'
provisioning_key = '{{cfg.shield_provisioning_key}}'
{{ /if }}
[[targets]]
name = '{{svc.service}}-{{svc.group}}'
plugin = 'fs'
[targets.config]
base_dir = '{{pkg.svc_data_path}}'
bsdtar = '{{pkgPathFor "core/libarchive"}}/bin/bsdtar'

[[stores]]
name = '{{svc.service}}-{{svc.group}}'
plugin = 's3'
[stores.config]
access_key_id = '{{cfg.aws_access_key}}'
secret_access_key = '{{cfg.aws_secret_key}}'
bucket = '{{cfg.aws_bucket}}'
prefix = '{{svc.service}}-{{svc.group}}'

{{ #if cfg.backups_schedule_value }}
[schedules]
{{cfg.backups_schedule}} = '{{cfg.backups_schedule_value}}'
{{ /if }}

{{ #if cfg.backups_retention_value }}
[retention-policies]
{{cfg.backups_retention}} = '{{cfg.backups_retention_value}}'
{{ /if }}

[[jobs]]
name = '{{svc.service}}-{{svc.group}}'
target = '{{svc.service}}-{{svc.group}}'
store = '{{svc.service}}-{{svc.group}}'
retention = '{{cfg.backups_retention}}'
schedule = '{{cfg.backups_schedule}}'
