{{ #if cfg.shield_endpoint }}
shield_endpoint = '{{cfg.shield_endpoint}}'
skip_ssl_verify = '{{cfg.shield_skip_ssl_verify}}'
provisioning_key = '{{cfg.shield_provisioning_key}}'
{{ /if }}
[[targets]]
name = '{{svc.service}}-{{svc.group}}'
plugin = 'fs'
[targets.config]
base_dir = '{{pkg.svc_data_path}}'
bsdtar = '{{pkgPathFor "core/libarchive"}}/bin/bsdtar'

{{ #if cfg.backups_schedule_value }}
[schedules]
{{cfg.backups_schedule}} = '{{cfg.backups_schedule_value}}'
{{ /if }}

{{ #if cfg.backups_retention_value }}
[retention-policies]
{{cfg.backups_retention}} = '{{cfg.backups_retention_value}}'
{{ /if }}

[[jobs]]
name = '{{svc.service}}-{{svc.group}}'
target = '{{svc.service}}-{{svc.group}}'
store = '{{cfg.backup_store}}'
retention = '{{cfg.backups_retention}}'
schedule = '{{cfg.backups_schedule}}'
