---
meta:
  dockerhub:
    email: (( vault "secret/pipelines/habitat-plans/dockerhub:email" ))
    username: (( vault "secret/pipelines/habitat-plans/dockerhub:username" ))
    password: (( vault "secret/pipelines/habitat-plans/dockerhub:password" ))
  habitat:
    origin_key: (( vault "secret/pipelines/habitat-plans/habitat:origin_key" ))
    auth_token: (( vault "secret/pipelines/habitat-plans/habitat:auth_token" ))
    origin: starkandwayne

groups:
- name: images
  jobs: [build-habitat-plans-pipeline-image]

jobs:
- name: build-habitat-plans-pipeline-image
  public: true
  plan:
  - aggregate:
    - {get: habitat-plans-pipeline, trigger: true}
    - {get: habitat-release, trigger: true}
  - put: habitat-plans-pipeline-image
    params:
      build: habitat-plans-pipeline/images/habitat-plans-pipeline
      tag: habitat-release/version
      tag_as_latest: true

resources:
- name: habitat-plans-pipeline
  type: git
  source:
    uri: https://github.com/starkandwayne/habitat-plans.git
    paths: [images/habitat-plans-pipeline/*]

- name: habitat-release
  type: github-release
  source:
    user:         habitat-sh
    repository:   habitat

- name: habitat-plans-pipeline-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: starkandwayne/habitat-plans-pipeline

resource_types:
- name: hab-pkg
  type: docker-image
  source:
    repository: starkandwayne/habitat-resource
