groups:
- jobs:
  - build-docker
  - build-postgresql
  - build-shield
  name: packages
- jobs:
  - build-habitat-plans-pipeline-image
  name: images
jobs:
- name: build-habitat-plans-pipeline-image
  plan:
  - aggregate:
    - get: habitat-plans-pipeline
      trigger: true
    - get: habitat-release
      trigger: true
  - params:
      build: habitat-plans-pipeline/images/habitat-plans-pipeline
      tag: habitat-release/version
      tag_as_latest: true
    put: habitat-plans-pipeline-image
  public: true
- name: build-postgresql
  plan:
  - aggregate:
    - get: core-bash
      trigger: true
    - get: core-glibc
      trigger: true
    - get: core-libossp-uuid
      trigger: true
    - get: core-openssl
      trigger: true
    - get: core-perl
      trigger: true
    - get: core-readline
      trigger: true
    - get: core-zlib
      trigger: true
    - get: postgresql-plan
      trigger: true
    - get: habitat-plans-ci
  - config:
      image: docker:///starkandwayne/habitat-plans-pipeline
      inputs:
      - name: postgresql-plan
      - name: habitat-plans-ci
      outputs:
      - name: result
      params:
        HAB_ORIGIN: starkandwayne
        HAB_ORIGIN_KEY: REDACTED
        OUT: result
        PACKAGE_CONTEXT: postgresql-plan/postgresql
        PLAN_NAME: postgresql
      platform: linux
      run:
        path: ./habitat-plans-ci/ci/scripts/build
    privileged: true
    task: build-postgresql
  - aggregate:
    - params:
        load_file: result/starkandwayne-postgresql-docker.tar
        load_repository: starkandwayne/postgresql
        load_tag: habitat
        tag: result/docker_tag
      put: starkandwayne-postgresql-image
    - params:
        load_file: result/starkandwayne-postgresql-docker.tar
        load_repository: starkandwayne/postgresql
        load_tag: habitat
      put: starkandwayne-postgresql-edge-image
  - params:
      result: result
    put: starkandwayne-postgresql
  public: true
- name: build-shield
  plan:
  - aggregate:
    - get: core-busybox-static
      trigger: true
    - get: core-glibc
      trigger: true
    - get: starkandwayne-postgresql
      trigger: true
    - get: shield-plan
      trigger: true
    - get: habitat-plans-ci
  - config:
      image: docker:///starkandwayne/habitat-plans-pipeline
      inputs:
      - name: shield-plan
      - name: habitat-plans-ci
      outputs:
      - name: result
      params:
        HAB_ORIGIN: starkandwayne
        HAB_ORIGIN_KEY: REDACTED
        OUT: result
        PACKAGE_CONTEXT: shield-plan/shield
        PLAN_NAME: shield
      platform: linux
      run:
        path: ./habitat-plans-ci/ci/scripts/build
    privileged: true
    task: build-shield
  - aggregate:
    - params:
        load_file: result/starkandwayne-shield-docker.tar
        load_repository: starkandwayne/shield
        load_tag: habitat
        tag: result/docker_tag
      put: starkandwayne-shield-image
    - params:
        load_file: result/starkandwayne-shield-docker.tar
        load_repository: starkandwayne/shield
        load_tag: habitat
      put: starkandwayne-shield-edge-image
  - params:
      result: result
    put: starkandwayne-shield
  public: true
- name: build-docker
  plan:
  - aggregate:
    - get: docker-plan
      trigger: true
    - get: habitat-plans-ci
  - config:
      image: docker:///starkandwayne/habitat-plans-pipeline
      inputs:
      - name: docker-plan
      - name: habitat-plans-ci
      outputs:
      - name: result
      params:
        HAB_ORIGIN: starkandwayne
        HAB_ORIGIN_KEY: REDACTED
        OUT: result
        PACKAGE_CONTEXT: docker-plan/docker
        PLAN_NAME: docker
      platform: linux
      run:
        path: ./habitat-plans-ci/ci/scripts/build
    privileged: true
    task: build-docker
  - aggregate:
    - params:
        load_file: result/starkandwayne-docker-docker.tar
        load_repository: starkandwayne/docker
        load_tag: habitat
        tag: result/docker_tag
      put: starkandwayne-docker-image
    - params:
        load_file: result/starkandwayne-docker-docker.tar
        load_repository: starkandwayne/docker
        load_tag: habitat
      put: starkandwayne-docker-edge-image
  - params:
      result: result
    put: starkandwayne-docker
  public: true
resource_types:
- name: hab-pkg
  source:
    repository: starkandwayne/habitat-resource
  type: docker-image
resources:
- name: habitat-plans-pipeline
  source:
    paths:
    - images/habitat-plans-pipeline/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: habitat-plans-ci
  source:
    paths:
    - ci/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: habitat-release
  source:
    repository: habitat
    user: habitat-sh
  type: github-release
- name: habitat-plans-pipeline-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/habitat-plans-pipeline
    username: REDACTED
  type: docker-image
- name: core-bash
  source:
    name: bash
    origin: core
  type: hab-pkg
- name: core-glibc
  source:
    name: glibc
    origin: core
  type: hab-pkg
- name: core-libossp-uuid
  source:
    name: libossp-uuid
    origin: core
  type: hab-pkg
- name: core-openssl
  source:
    name: openssl
    origin: core
  type: hab-pkg
- name: core-perl
  source:
    name: perl
    origin: core
  type: hab-pkg
- name: core-readline
  source:
    name: readline
    origin: core
  type: hab-pkg
- name: core-zlib
  source:
    name: zlib
    origin: core
  type: hab-pkg
- name: core-busybox-static
  source:
    name: busybox-static
    origin: core
  type: hab-pkg
- name: starkandwayne-postgresql
  source:
    auth_token: REDACTED
    name: postgresql
    origin: starkandwayne
  type: hab-pkg
- name: starkandwayne-docker
  source:
    auth_token: REDACTED
    name: docker
    origin: starkandwayne
  type: hab-pkg
- name: docker-plan
  source:
    paths:
    - docker/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: starkandwayne-docker-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/docker
    username: REDACTED
  type: docker-image
- name: starkandwayne-docker-edge-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/docker
    tag: edge
    username: REDACTED
  type: docker-image
- name: postgresql-plan
  source:
    paths:
    - postgresql/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: starkandwayne-postgresql-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/postgresql
    username: REDACTED
  type: docker-image
- name: starkandwayne-postgresql-edge-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/postgresql
    tag: edge
    username: REDACTED
  type: docker-image
- name: starkandwayne-shield
  source:
    auth_token: REDACTED
    name: shield
    origin: starkandwayne
  type: hab-pkg
- name: shield-plan
  source:
    paths:
    - shield/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: starkandwayne-shield-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/shield
    username: REDACTED
  type: docker-image
- name: starkandwayne-shield-edge-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/shield
    tag: edge
    username: REDACTED
  type: docker-image

