groups:
- jobs:
  - build-postgresql
  - build-shield
  name: packages
- jobs:
  - build-habitat-plans-pipeline-image
  name: images
jobs:
- name: build-habitat-plans-pipeline-image
  plan:
  - aggregate:
    - get: habitat-plans-pipeline
      trigger: true
    - get: habitat-release
      trigger: true
  - params:
      build: habitat-plans-pipeline/images/habitat-plans-pipeline
      tag: habitat-release/version
      tag_as_latest: true
    put: habitat-plans-pipeline-image
  public: true
- name: build-postgresql
  plan:
  - aggregate:
    - get: core-bash
      trigger: true
    - get: core-glibc
      trigger: true
    - get: core-libossp-uuid
      trigger: true
    - get: core-openssl
      trigger: true
    - get: core-perl
      trigger: true
    - get: core-readline
      trigger: true
    - get: core-zlib
      trigger: true
  - get: postgresql-plan
    trigger: true
  - config:
      image: docker:///starkandwayne/habitat-plans-pipeline
      inputs:
      - name: postgresql-plan
      outputs:
      - name: result
      params:
        HAB_ORIGIN: starkandwayne
        HAB_ORIGIN_KEY: REDACTED
        OUT: result
        PACKAGE_CONTEXT: postgresql-plan/postgresql
      platform: linux
      run:
        path: ./postgresql-plan/ci/scripts/build
    privileged: true
    task: build-postgresql
  - params:
      result: result
    put: starkandwayne-postgresql
  public: true
- name: build-shield
  plan:
  - aggregate:
    - get: core-busybox-static
      trigger: true
    - get: core-glibc
      trigger: true
    - get: starkandwayne-postgresql
      trigger: true
  - get: shield-plan
    trigger: true
  - config:
      image: docker:///starkandwayne/habitat-plans-pipeline
      inputs:
      - name: shield-plan
      outputs:
      - name: result
      params:
        HAB_ORIGIN: starkandwayne
        HAB_ORIGIN_KEY: REDACTED
        OUT: result
        PACKAGE_CONTEXT: shield-plan/shield
      platform: linux
      run:
        path: ./shield-plan/ci/scripts/build
    privileged: true
    task: build-shield
  - params:
      result: result
    put: starkandwayne-shield
  public: true
resource_types:
- name: hab-pkg
  source:
    repository: starkandwayne/habitat-resource
  type: docker-image
resources:
- name: habitat-plans-pipeline
  source:
    paths:
    - images/habitat-plans-pipeline/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: habitat-release
  source:
    repository: habitat
    user: habitat-sh
  type: github-release
- name: habitat-plans-pipeline-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/habitat-plans-pipeline
    username: REDACTED
  type: docker-image
- name: core-bash
  source:
    name: bash
    origin: core
  type: hab-pkg
- name: core-glibc
  source:
    name: glibc
    origin: core
  type: hab-pkg
- name: core-libossp-uuid
  source:
    name: libossp-uuid
    origin: core
  type: hab-pkg
- name: core-openssl
  source:
    name: openssl
    origin: core
  type: hab-pkg
- name: core-perl
  source:
    name: perl
    origin: core
  type: hab-pkg
- name: core-readline
  source:
    name: readline
    origin: core
  type: hab-pkg
- name: core-zlib
  source:
    name: zlib
    origin: core
  type: hab-pkg
- name: core-busybox-static
  source:
    name: busybox-static
    origin: core
  type: hab-pkg
- name: starkandwayne-postgresql
  source:
    auth_token: REDACTED
    name: postgresql
    origin: starkandwayne
  type: hab-pkg
- name: postgresql-plan
  source:
    paths:
    - postgresql/*
    - ci/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git
- name: starkandwayne-shield
  source:
    auth_token: REDACTED
    name: shield
    origin: starkandwayne
  type: hab-pkg
- name: shield-plan
  source:
    paths:
    - shield/*
    - ci/*
    uri: https://github.com/starkandwayne/habitat-plans.git
  type: git

